---
name: project_quran
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  google_fonts: ^1.1.0
  audioplayers: ^0.16.1
  font_awesome_flutter: ^8.8.1
  provider: ^4.3.2+2
  flutter_playout: ^1.0.41
  audio_service: ^0.11.0
  just_audio: ^0.2.1
  lottie: ^0.6.0
  modal_bottom_sheet: ^0.2.2
  #  sliding_up_panel:
  shared_preferences: ^0.5.12+2
  audioplayer: null
  #  flutter_tawk: any
  flutter_screenutil: ^3.1.1
  url_launcher: null
  #  ext_storage: null
  popup_menu: null
  badges: null
  get: ^3.13.2
  share: ^0.6.5+3
  quick_actions: ^0.4.0+10
  animated_splash_screen: ^1.0.1+2
  flutter_svg: any
  motion_tab_bar: ^0.1.5
  statusbar_util: ^1.0.1
  in_app_review: null
  pdf_flutter: any
  launch_review: ^2.0.0
  path_provider: null
  flutter_full_pdf_viewer: any
  flutter_pdfview: null
  locales: ^0.1.0
  advance_pdf_viewer: ^1.2.0
  permission_handler: ^4.2.0+hotfix.1
  dio: null
  intl: null
  epub_viewer: ^0.1.9
  flutter_fullpdfview: ^1.1.5
  syncfusion_flutter_pdfviewer: ^18.3.44-beta
  panorama: ^0.0.2
  morpheus: null
  marquee: null
  shimmer: null
  rubber: ^0.2.7
  native_pdf_view: ^2.1.1
  screen: ^0.0.5
  device_info: ^0.4.1+4
  adaptive_breakpoints: ^0.0.2
#  story_view: any
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/audio/Amma/
    - assets/images/
    - assets/lottie/
    - assets/json/
    - assets/
